### ISSUE TITLE
كتابة نصوص اكثر تعقيداً

### ISSUE THREAD

**Issue by ahmed4end** [asgore-undertale/Python-Arabic-reshaping-code#1]
بعض الخطوط لا تتبع القاعدة البسيطة للحروف كحرف فالبداية ومالنتصف والنهاية مثل:
![92096084-c7420b80-edd6-11ea-8035-d8a02afe5818](https://user-images.githubusercontent.com/35382418/101309265-a3b6b300-3854-11eb-8982-4b734f872c23.png)

لاحظ عند حدوث ان حرف السين فالبداية ويليه حرف الياء والميم يتم تغيير شكلهم كالتالى !
اسم الخط المستخدم : Arabic typesetting

**Comment by asgore-undertale** [comment]
هذا لن يحدث مشكلة اذ انه من الخط نفسه،
او ممكن ان يكون حرفا مدمجا والحروف المدمجة دوما ما تكون مجمدة.
